### ISSUE TITLE
Make from/to date range overridable in admin

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#256]
e.g. France has a "5021" typo in its data, and another source (or maybe France again) has a minimum year of "21": https://data.open-contracting.org/en/publication/23

Also, some publications don't set the date correctly (they set it to the current/retrieval date), so we will need to override those as well (I think Argentina Vialidad).

I think this field is currently a property of the job (which makes sense). For the override, we would put it on the publication itself (and we'll need to remember to change the end date periodically).

**Comment by jpmckinney** [comment]
We can also add an admin filter to check for future "to" dates (and/or early "from" dates).

**Comment by jpmckinney** [comment]
I fixed the impossible dates by limiting Kingfisher Process's metadata endpoint to > Unix epoch and <= today.

> some publications don't set the date correctly (they set it to the current/retrieval date), so we will need to override those as well (I think Argentina Vialidad).

This issue could remain open for this reason, but ...

> we'll need to remember to change the end date periodically

That's too much overhead. So, we can just make a note in the quality issues.

FWIW, Vialidad seems to not have the issue anymore: https://data.open-contracting.org/en/publication/18

**Comment by yolile** [comment]
> FWIW, Vialidad seems to not have the issue anymore: https://data.open-contracting.org/en/publication/18

Hmm well, they are not setting it to the current date but the dates are still incorrect.

**Comment by jpmckinney** [comment]
Does anyone else have known incorrect dates (between 1970 and today)?

**Comment by yolile** [comment]
Yes, Indonesia Corruption Watch, for example https://data.open-contracting.org/es/publication/101

**Comment by jpmckinney** [comment]
With the updated query in Kingfisher Process their dates will be in a reasonable range (see above commit). Will they have incorrect dates even within that range?

**Comment by yolile** [comment]
I think your fix will work (the files will still be segmented by all the available years though, right?)

**Comment by jpmckinney** [comment]
Yeah, the exporter worker reads directly from Kingfisher Process without applying similar conditions/filters.

**Comment by yolile** [comment]
It also happens in Paraguay Hacienda https://data.open-contracting.org/es/publication/62 but they are not updating their data anymore anyway so I think we can leave the issue closed

**Comment by yolile** [comment]
Note that the original discussion in this issue was about overriding the from/to date for existing jobs. However, for unretrieved publications, we don't have a job at all, and want to also set the other overview fields: ocid prefix and license, so for implementing this, we should:

> For the override, we would put it on the publication itself (and we'll need to remember to change the end date periodically).
