### ISSUE TITLE
Datasets should be in alphabetical order

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#73]
When the user first lands on this page, the datasets should automatically appear in alphabetical order:

<img width="841" alt="Screenshot 2021-06-17 154437" src="https://user-images.githubusercontent.com/11212467/122419663-fcdd6d00-cf82-11eb-852d-6fab546b05e0.png">

**Comment by sabahfromlondon** [comment]
Same for when a user select a letter. Here the order should be: Afghanistan Records, Australia Department of finance, Australia New South Wales, Austria Digiwhist.

<img width="840" alt="Screenshot 2021-06-17 154645" src="https://user-images.githubusercontent.com/11212467/122420037-45952600-cf83-11eb-9c3d-361c5f643637.png">

**Comment by t-mrazek** [comment]
fixed

**Comment by sabahfromlondon** [comment]
@t-mrazek @hrubyjan I'm testing again and this is still an issue. Is there something I'm doing wrong?

**Comment by sabahfromlondon** [comment]
Checked again after Jakub pushed the fixes live. Looks good this time :)

**Comment by jpmckinney** [comment]
Closing as Deployed.
